version: '3'

services:
  apache:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      -  ./:/var/www/html
    depends_on:
      - php

  php:
    build:
      ./docker/php
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html/public
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.1
    restart: unless-stopped
    container_name: db
    volumes:
      - ./docker/config:/etc/mysql/conf.d
      - ./docker/databases:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=buh
      - MYSQL_DATABASE=buh
      - MYSQL_USER=buh
    command:
      mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080